version: "3"
services:
  kademlia:
    image: kademlia:latest
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - kademlia_net
    ports:
     - "8000/udp"
  kademlia_tracker:
    image: kademlia_tracker:latest
    stdin_open: true
    tty: true
    networks:
      - kademlia_net
networks: 
  kademlia_net:
